### ISSUE TITLE
Add system configuration to check if the JavaScript snippet should be added to the header.

### ISSUE THREAD

**Issue by grafikchaos** [augustash/magento2-module-facebookpixel#3]
Since the Facebook Pixel can be added via Google Tag Manager and clients may use other 3rd party companies for managing their GTM containers, we should have a way to control whether this module adds the javascript snippet to the header or not to avoid potentially creating duplicates of the javascript snippet and double reporting of the tracking.

See https://github.com/augustash/magento2-module-facebookpixel/blob/313bb757537dbadd9de03d310a77ef41c3c32349/view/frontend/templates/snippet.phtml#L2

**Comment by kazajhodo** [comment]
Done. There is now an admin option in the advanced section to turn off the snippet inclusion.
